### ISSUE TITLE
Change the name of repository

### ISSUE THREAD

**Issue by tralynca** [hocinebendou/tb_operon_detection#2]
Hey Hocine,

Will we be able to change the name of the repository to COSMO please. We've agreed that this predictor doesn't just work on TB, but can be used to predict operons for other microorganisms.

**Comment by tralynca** [comment]
I've tried to change the name on my fork, but it doesn't allow for a pull request to be created. The same with the About Page. It's supposed to say for microorganisms and **not** for Myocbacterrium tuberculosis

**Comment by pvanheus** [comment]
Done.
